### ISSUE TITLE
Ubuntu 22.04 Support?

### ISSUE THREAD

**Issue by Torchtopher** [berndpfrommer/tagslam_root#18]
Are there any plans for support for 22.04? I am trying to install tagslam and running into lots of issues with gstam. The suggested method in the wiki does not work as that ppa is not available for 22.04. Installing both from source and from the ppas on gstam's website both give gstam related build errors. Has anyone had success with building for 22.04 or know how to do it?

**Comment by berndpfrommer** [comment]
I feared this issue coming up. The problem is that ROS1 is no longer supported on Ubuntu 22.04. You will have to build ROS1 noetic from sources to use it on Ubuntu 22.04.
If you are ready to go through these hoops, here's what you can do about GTSAM: install release 4.1. TagSLAM should compile with it.
I created this PPA very recently. Please give it a spin and let me know how it works:
https://launchpad.net/~borglab/+archive/ubuntu/gtsam-release-4.1

Thanks!

**Comment by berndpfrommer** [comment]
I was planning of starting a new version of TagSLAM for ROS2. Would you be able to transition to ROS2?

**Comment by Torchtopher** [comment]
Thanks for the quick response! I tried the PPA you suggested and get a different error about GSTAM version (see picture). Not sure if there is a fix for this. We have a large ROS1 codebase currently on noetic that we are not going to be able to port to ROS2 anytime soon.
![tagslam](https://user-images.githubusercontent.com/88154155/214121545-ebbca7aa-40f2-4956-8c7b-bb18abb80786.png)

**Comment by berndpfrommer** [comment]
Something else is going on. Do  you have another version of gtsam installed
somewhere? It seems to have linked against gtsam 4.3.0. But the one you get
from the new ppa is 4.1.1.

**Comment by Torchtopher** [comment]
Thanks, realized our docker containers had the more recent version installed. Removed that and installed yours and it worked! Now builds and tests run successfully.
