### ISSUE TITLE
catkin build errors.

### ISSUE THREAD

**Issue by ZitongLan** [berndpfrommer/tagslam_root#21]
![Screenshot from 2023-12-05 11-49-44](https://github.com/berndpfrommer/tagslam_root/assets/57742620/620a6054-655b-4d23-bbff-b5db9dbf94ad)

Hello! I am trying to implement the TagSlam on my local ubuntu machine 22.04. I install ROS 2 on my computer. And follow the instrucions of installation of TagSlam, when I do `catkin build` command. Above error messages pop out. Since I am new to ROS operating system, is there anything wrong in these error messages?

**Comment by berndpfrommer** [comment]
Sadly, TagSLAM only currently compiles and runs under ROS1, not ROS2.
Even worse, ROS1 cannot be installed easily on Ubuntu 22.04, because ROS1 support has stopped with Ubuntu 20.04.
There is an issue open regarding this (#20 ) but it's not clear when and if I'll get around to porting TagSLAM to ROS2.
