### ISSUE TITLE
message_filters

### ISSUE THREAD

**Issue by e-guy** [berndpfrommer/tagslam_root#5]
Hi Bernd,

It seems flex_sync::SubscribingSync<TagArray, Image, Odometry> makes sure that callback function can be triggered only when different types of msgs have the same timestamp but not aproximate timestamp. This policy is quite like sync_policies::ExactTime but not 
 message_filters.ApproximateTimeSynchronizer. As a result, callback function cannot be triggered when I tested with my rosbag which contains both tagarray msgs and odometry msgs.

**Comment by berndpfrommer** [comment]
Alas, you are correct: the time stamps need to be identical, not just approximately, but exactly.
I wrote the flex_sync stuff because the original ROS message filters require committing to a fixed number of topics and corresponding times. The code gets a mess. I very much like they approximate time sync class, but it's not easy code to read, and I didn't feel like lifting it out and generalizing it. In particular since the odom I was using always came from the same cameras that were detecting the tags, so the time stamps were identical.

So how to work around the issue? Here some possibilities:
1) Write a separate node that subscribes to tag and odom topics using the ros message filters with approx time sync, then publishes the time-synced odom under a different topic, with header.stamp set to the tag time stamp
2) Process the bag with a python script, cache the tag time stamps and the odom. Interpolate odom to the nearest tag time stamp, and write it to the bag under a new topic.

My preferred solution would be 2), because it allows for interpolation. Will you be working from bags only, or does that have to run real-time? Note that running real-time for SLAM is generally not a good idea because there is no bound on the time the optimizer can take.

**Comment by e-guy** [comment]
Thank you very much. I may need choose the first suggestion for supporting real-time running. As for time consuming of optimizer, may I  build map offline (notes that my map is enclosed) and  then run real-time locating?

**Comment by berndpfrommer** [comment]
If you have a map already, then you can use the "amnesia" feature such that the graph is truncated. That should allow you to run in real time.

**Comment by berndpfrommer** [comment]
As of right now, tagslam does support approximate sync:

https://github.com/berndpfrommer/tagslam/commit/542b555b6d5c5a62bfedfd2245ccee2156bd818f
