### ISSUE TITLE
Error with submodule tagslam:  gtsam::transform_from()

### ISSUE THREAD

**Issue by matheusbg8** [berndpfrommer/tagslam_root#7]
Hi Bernd Pfrommer,

I am having issues to build your code [catkin_output.txt](https://github.com/berndpfrommer/tagslam_root/files/4401708/catkin_output.txt). In submodule tagslam you are using gtsam::transform_from in multiple places on file tagslam/src/gtsam_optimizer.cpp:173 , however transform_from is not a member of gtsam.

I am using gtsam from your repository ppa:bernd-pfrommer/gtsam.

Do you know why I am having this issue?

There are some code injections on namespace gtsam but none of them include transform_from.

Regards,
Matheus

**Comment by berndpfrommer** [comment]
Matheus,

The error message you are seeing is almost certainly an indicator that there is another version of GTSAM installed on your system, which is used instead of the one from the ppa. Can you run catkin build -v to see what is actually being included from?

Have a look at this thread as well:

https://groups.google.com/forum/#!searchin/tagslam/transform_from%7Csort:date/tagslam/9pehO8_G7is/hUHD4bQOBAAJ

**Comment by matheusbg8** [comment]
Hi Bernd Pfrommer,

   You were right. I found another GTSAM installed in my system at /usr/local/lib/cmake/GTSAM/../../../include . I was using GTSAM from https://bitbucket.org/gtborg/gtsam.git . I had to use command checkinstall and follow the instructions of Nisse in https://stackoverflow.com/questions/1439950/whats-the-opposite-of-make-install-i-e-how-do-you-uninstall-a-library-in-li to uninstall the previous library because they do not provide a make uninstall.
    After removing the previous library and installing the version from your ppa, everything builds with no errors.

Thank you!
